import { BusinessType } from '@/types';

export const PRESET_BUSINESS_TYPES: BusinessType[] = [
  {
    id: 'kirana',
    name: 'Kirana / Grocery Store',
    icon: 'Store',
    description: 'Fast barcode POS, loose grains, weights, MRP, batches and expiry',
    category: 'RETAIL',
    defaultModules: ['billing', 'inventory', 'customers', 'suppliers', 'expenses', 'reports', 'gst', 'barcode'],
    defaultCategories: ['Grains & Pulses', 'Oils & Ghee', 'Spices', 'Snacks', 'Beverages', 'Dairy', 'Personal Care', 'Cleaning'],
    defaultUnits: ['KG', 'Gram', 'Litre', 'ML', 'Packet', 'Piece', 'Box'],
    defaultTaxRate: 5,
    isSystem: true,
    customFields: [
      { id: 'f_weight', name: 'Net Weight / Pack Size', key: 'weight', type: 'text', placeholder: 'e.g. 1 Kg / 500g' },
      { id: 'f_batch', name: 'Batch No', key: 'batchNo', type: 'text', placeholder: 'e.g. BATCH-2026-09' },
      { id: 'f_expiry', name: 'Expiry Date', key: 'expiryDate', type: 'date' },
      { id: 'f_mfg', name: 'Mfg Date', key: 'mfgDate', type: 'date' },
      { id: 'f_fssai', name: 'FSSAI License No', key: 'fssaiNumber', type: 'text', placeholder: '14-digit FSSAI Lic' },
    ],
  },
  {
    id: 'medical_pharmacy',
    name: 'Medical / Pharmacy',
    icon: 'Pill',
    description: 'Strict batch and expiry tracking, generic composition, manufacturer and prescription alerts',
    category: 'HEALTHCARE',
    defaultModules: ['billing', 'inventory', 'customers', 'suppliers', 'expenses', 'reports', 'gst', 'barcode', 'returns'],
    defaultCategories: ['Tablets', 'Syrups', 'Injections', 'Ointments', 'Medical Devices', 'Ayurvedic', 'Baby Care', 'Nutritional'],
    defaultUnits: ['Strip', 'Bottle', 'Piece', 'Box', 'Tube', 'Vial'],
    defaultTaxRate: 12,
    isSystem: true,
    customFields: [
      { id: 'f_batch_med', name: 'Batch Number', key: 'batchNo', type: 'text', required: true, placeholder: 'e.g. BATCH-892A' },
      { id: 'f_expiry_med', name: 'Expiry Date', key: 'expiryDate', type: 'date', required: true },
      { id: 'f_generic', name: 'Generic / Salt Composition', key: 'genericName', type: 'text', required: true, placeholder: 'e.g. Paracetamol 500mg' },
      { id: 'f_mfg_comp', name: 'Manufacturer / Brand', key: 'manufacturer', type: 'text', placeholder: 'e.g. Cipla, Sun Pharma, Abbott' },
      { id: 'f_drug_schedule', name: 'Drug Schedule', key: 'drugSchedule', type: 'dropdown', options: ['OTC (General)', 'Schedule H', 'Schedule H1', 'Schedule G', 'Narcotic'] },
      { id: 'f_rx_required', name: 'Prescription Required (Rx)', key: 'prescriptionRequired', type: 'boolean', defaultValue: false },
    ],
  },
  {
    id: 'garments_footwear',
    name: 'Garments & Footwear',
    icon: 'Shirt',
    description: 'Fashion apparel & footwear with size, color, fabric, gender, and styles',
    category: 'RETAIL',
    defaultModules: ['billing', 'inventory', 'customers', 'suppliers', 'expenses', 'reports', 'gst', 'barcode', 'returns'],
    defaultCategories: ["Men's Wear", "Women's Wear", "Kids Wear", "Footwear (Men)", "Footwear (Women)", "Ethnic Wear", "Accessories"],
    defaultUnits: ['Piece', 'Pair', 'Set', 'Meter', 'Box'],
    defaultTaxRate: 5,
    isSystem: true,
    customFields: [
      { id: 'f_size', name: 'Size', key: 'size', type: 'dropdown', options: ['XS', 'S', 'M', 'L', 'XL', 'XXL', '3XL', '28', '30', '32', '34', '36', '38', '40', 'UK-5', 'UK-6', 'UK-7', 'UK-8', 'UK-9', 'UK-10', 'Free Size'] },
      { id: 'f_color', name: 'Color / Shade', key: 'color', type: 'text', placeholder: 'e.g. Navy Blue, Maroon' },
      { id: 'f_fabric', name: 'Fabric / Material', key: 'fabric', type: 'text', placeholder: 'e.g. Pure Cotton, Silk, Denim, Leather' },
      { id: 'f_gender', name: 'Gender Target', key: 'gender', type: 'dropdown', options: ['Men', 'Women', 'Boys', 'Girls', 'Unisex', 'Kids'] },
      { id: 'f_pattern', name: 'Pattern / Style', key: 'pattern', type: 'text', placeholder: 'e.g. Printed, Checked, Plain, Formal' },
    ],
  },
  {
    id: 'electronics_mobile',
    name: 'Electronics & Mobile',
    icon: 'Smartphone',
    description: 'IMEI / serial tracking, brand, model, warranty months, specifications',
    category: 'RETAIL',
    defaultModules: ['billing', 'inventory', 'customers', 'suppliers', 'expenses', 'reports', 'gst', 'barcode', 'returns'],
    defaultCategories: ['Smartphones', 'Feature Phones', 'Audio & Earbuds', 'Chargers & Accessories', 'Laptops & Tablets', 'Home Appliances'],
    defaultUnits: ['Piece', 'Set', 'Box'],
    defaultTaxRate: 18,
    isSystem: true,
    customFields: [
      { id: 'f_imei1', name: 'IMEI 1 / Serial No', key: 'imei1', type: 'text', placeholder: '15-digit IMEI or Serial' },
      { id: 'f_brand_elec', name: 'Brand', key: 'brand', type: 'text', placeholder: 'e.g. Apple, Samsung, LG, HP' },
      { id: 'f_model_no', name: 'Model Number', key: 'modelNo', type: 'text', placeholder: 'e.g. iPhone 15 Pro / Galaxy S24' },
      { id: 'f_ram_rom', name: 'RAM / Storage / Specs', key: 'ramRom', type: 'text', placeholder: 'e.g. 8GB / 256GB' },
      { id: 'f_warranty_months', name: 'Warranty (Months)', key: 'warrantyMonths', type: 'number', placeholder: '12' },
    ],
  },
  {
    id: 'hardware_paints',
    name: 'Hardware & Paints',
    icon: 'Wrench',
    description: 'Paints, shade codes, pipes, tools, sanitary fixtures, industrial hardware',
    category: 'RETAIL',
    defaultModules: ['billing', 'inventory', 'customers', 'suppliers', 'expenses', 'reports', 'gst', 'barcode'],
    defaultCategories: ['Paints & Enamels', 'Wall Putty & Primers', 'Pipes & Fittings', 'Sanitary Ware', 'Hand Tools', 'Fasteners & Screws'],
    defaultUnits: ['Piece', 'Litre', 'KG', 'Meter', 'Feet', 'Roll', 'Box'],
    defaultTaxRate: 18,
    isSystem: true,
    customFields: [
      { id: 'f_shade_code', name: 'Paint Shade Code', key: 'shadeCode', type: 'text', placeholder: 'e.g. AP-091 Royal Blue' },
      { id: 'f_finish_type', name: 'Finish Type', key: 'finishType', type: 'dropdown', options: ['Gloss', 'Matte', 'Satin', 'Semi-Gloss', 'Exterior Primer', 'Textured'] },
      { id: 'f_material_grade', name: 'Material Grade / Gauge', key: 'materialGrade', type: 'text', placeholder: 'e.g. SS-304, CPVC Class 1' },
      { id: 'f_pack_size_hard', name: 'Pack Size / Dimension', key: 'packSize', type: 'text', placeholder: 'e.g. 1L, 4L, 20L, 1/2 Inch' },
    ],
  },
  {
    id: 'restaurant_cafe',
    name: 'Restaurant / Cafe',
    icon: 'Utensils',
    description: 'Dine-in, takeaway, dietary tags, spice levels, portion sizing and prep times',
    category: 'FOOD_BEVERAGE',
    defaultModules: ['billing', 'inventory', 'customers', 'expenses', 'reports', 'gst'],
    defaultCategories: ['Starters', 'Main Course', 'Breads & Rice', 'Beverages', 'Desserts', 'Snacks', 'Combos'],
    defaultUnits: ['Plate', 'Portion', 'Glass', 'Piece', 'Cup'],
    defaultTaxRate: 5,
    isSystem: true,
    customFields: [
      { id: 'f_diet_type', name: 'Dietary Type', key: 'dietType', type: 'dropdown', options: ['Veg', 'Non-Veg', 'Egg', 'Vegan', 'Jain'] },
      { id: 'f_spice_level', name: 'Spice Level', key: 'spiceLevel', type: 'dropdown', options: ['Mild', 'Medium', 'Spicy', 'Extra Hot'] },
      { id: 'f_prep_time', name: 'Prep Time (Mins)', key: 'prepTime', type: 'number', placeholder: '15' },
      { id: 'f_portion', name: 'Portion Size', key: 'portion', type: 'dropdown', options: ['Single', 'Half', 'Full', 'Family Pack'] },
    ],
  },
  {
    id: 'sweet_bakery',
    name: 'Sweet Shop / Bakery',
    icon: 'Cake',
    description: 'Fresh sweets, bakery items, shelf life tracking, eggless labels, allergens',
    category: 'FOOD_BEVERAGE',
    defaultModules: ['billing', 'inventory', 'customers', 'expenses', 'reports', 'gst', 'barcode'],
    defaultCategories: ['Milk Sweets', 'Dry Fruit Sweets', 'Cakes & Pastries', 'Breads & Buns', 'Cookies & Biscuits', 'Snacks & Namkeen'],
    defaultUnits: ['KG', 'Gram', 'Piece', 'Box', 'Packet'],
    defaultTaxRate: 5,
    isSystem: true,
    customFields: [
      { id: 'f_shelf_life', name: 'Shelf Life (Days)', key: 'shelfLifeDays', type: 'number', placeholder: 'e.g. 3' },
      { id: 'f_eggless', name: 'Eggless', key: 'eggless', type: 'boolean', defaultValue: true },
      { id: 'f_serving_wt', name: 'Serving Pack Size', key: 'servingWeight', type: 'text', placeholder: 'e.g. 250g, 500g, 1 Kg' },
      { id: 'f_key_ingredients', name: 'Key Ingredients', key: 'ingredients', type: 'text', placeholder: 'e.g. Mawa, Kaju, Pure Desi Ghee' },
    ],
  },
  {
    id: 'stationery_books',
    name: 'Stationery & Books',
    icon: 'BookOpen',
    description: 'School/office supplies, textbooks, authors, publishers, ISBNs',
    category: 'RETAIL',
    defaultModules: ['billing', 'inventory', 'customers', 'suppliers', 'expenses', 'reports', 'gst', 'barcode'],
    defaultCategories: ['Notebooks & Registers', 'Pens & Writing', 'Textbooks', 'Office Stationery', 'Art & Craft', 'Calculators & Geometry'],
    defaultUnits: ['Piece', 'Dozen', 'Packet', 'Set', 'Box'],
    defaultTaxRate: 12,
    isSystem: true,
    customFields: [
      { id: 'f_author_brand', name: 'Author / Brand / Publisher', key: 'authorBrand', type: 'text', placeholder: 'e.g. NCERT, Classmate, Reynolds' },
      { id: 'f_isbn', name: 'ISBN / Edition', key: 'isbn', type: 'text', placeholder: 'e.g. 978-3-16-148410-0' },
      { id: 'f_class_grade', name: 'Class / Grade / Purpose', key: 'classGrade', type: 'text', placeholder: 'e.g. Class 10th / Office Use' },
      { id: 'f_binding', name: 'Format / Binding', key: 'binding', type: 'dropdown', options: ['Paperback', 'Hardcover', 'Spiral Bound', 'Standard Pack'] },
    ],
  },
  {
    id: 'auto_parts',
    name: 'Auto Parts & Service',
    icon: 'Car',
    description: 'Vehicle spare parts, OEM numbers, model compatibility, garage service',
    category: 'RETAIL',
    defaultModules: ['billing', 'inventory', 'customers', 'suppliers', 'expenses', 'reports', 'gst', 'barcode'],
    defaultCategories: ['Engine Parts', 'Brake Systems', 'Lubricants & Oils', 'Electrical & Batteries', 'Tires & Tubes', 'Filters & Plugs'],
    defaultUnits: ['Piece', 'Set', 'Litre', 'Pair', 'Box'],
    defaultTaxRate: 18,
    isSystem: true,
    customFields: [
      { id: 'f_oem_part', name: 'OEM Part Number', key: 'oemPartNumber', type: 'text', placeholder: 'e.g. OEM-889123' },
      { id: 'f_compatible_model', name: 'Vehicle Compatibility', key: 'compatibleVehicle', type: 'text', placeholder: 'e.g. Maruti Swift 2018+, Hero Splendor' },
      { id: 'f_part_brand', name: 'Part Brand / Tier', key: 'partBrand', type: 'text', placeholder: 'e.g. Bosch, Minda, Castrol' },
      { id: 'f_warranty_auto', name: 'Warranty Period', key: 'warranty', type: 'text', placeholder: 'e.g. 6 Months / 1 Year' },
    ],
  },
  {
    id: 'jewellery',
    name: 'Jewellery',
    icon: 'Gem',
    description: 'Gold, silver, diamonds, karat purity, BIS hallmark, making charges, weights',
    category: 'RETAIL',
    defaultModules: ['billing', 'inventory', 'customers', 'suppliers', 'expenses', 'reports', 'gst', 'barcode'],
    defaultCategories: ['Gold Rings', 'Gold Chains', 'Bangles', 'Necklace Sets', 'Silver Articles', 'Diamond Ornaments'],
    defaultUnits: ['Gram', 'Milligram', 'Piece'],
    defaultTaxRate: 3,
    isSystem: true,
    customFields: [
      { id: 'f_purity', name: 'Purity / Karat', key: 'purity', type: 'dropdown', options: ['24K (99.9%)', '22K (91.6% Hallmark)', '18K (75.0%)', '14K', 'Silver 925'] },
      { id: 'f_gross_wt', name: 'Gross Weight (g)', key: 'grossWeight', type: 'number', placeholder: '0.000' },
      { id: 'f_net_wt', name: 'Net Weight (g)', key: 'netWeight', type: 'number', placeholder: '0.000' },
      { id: 'f_making_charge', name: 'Making Charge (₹/g or %)', key: 'makingCharge', type: 'text', placeholder: 'e.g. 12% or ₹450/g' },
      { id: 'f_huid', name: 'BIS Hallmark HUID Code', key: 'huid', type: 'text', placeholder: '6-character alphanumeric' },
    ],
  },
  {
    id: 'agriculture',
    name: 'Agriculture / Seeds & Fertilizer',
    icon: 'Wheat',
    description: 'Hybrid seeds, fertilizers, pesticides, NPK compositions, government subsidies',
    category: 'AGRICULTURE',
    defaultModules: ['billing', 'inventory', 'customers', 'suppliers', 'expenses', 'reports', 'gst', 'barcode'],
    defaultCategories: ['Hybrid Seeds', 'Chemical Fertilizers', 'Bio-Fertilizers', 'Pesticides & Insecticides', 'Irrigation Tools', 'Farming Equipment'],
    defaultUnits: ['KG', 'Bag (50kg)', 'Litre', 'Packet', 'Bottle'],
    defaultTaxRate: 5,
    isSystem: true,
    customFields: [
      { id: 'f_seed_variety', name: 'Seed / Crop Variety', key: 'seedVariety', type: 'text', placeholder: 'e.g. Hybrid Wheat 505' },
      { id: 'f_germination', name: 'Germination Rate (%)', key: 'germinationRate', type: 'text', placeholder: 'e.g. 85%' },
      { id: 'f_npk_formula', name: 'NPK / Chemical Formula', key: 'npkFormula', type: 'text', placeholder: 'e.g. 19:19:19 / Urea 46%' },
      { id: 'f_agri_expiry', name: 'Expiry / Season Date', key: 'expiryDate', type: 'date' },
    ],
  },
  {
    id: 'furniture',
    name: 'Furniture',
    icon: 'Armchair',
    description: 'Home & office furniture, wood types, dimensions, warranty, assembly',
    category: 'RETAIL',
    defaultModules: ['billing', 'inventory', 'customers', 'suppliers', 'expenses', 'reports', 'gst'],
    defaultCategories: ['Sofas & Couches', 'Dining Tables', 'Beds & Mattresses', 'Office Chairs & Desks', 'Wardrobes', 'Outdoor Furniture'],
    defaultUnits: ['Piece', 'Set'],
    defaultTaxRate: 18,
    isSystem: true,
    customFields: [
      { id: 'f_wood_material', name: 'Material / Wood Type', key: 'woodMaterial', type: 'dropdown', options: ['Teak Wood', 'Sheesham', 'Engineered Wood', 'Solid Oak', 'Metal / Steel', 'Leatherette'] },
      { id: 'f_dimensions', name: 'Dimensions (L x W x H)', key: 'dimensions', type: 'text', placeholder: 'e.g. 72 x 36 x 30 inches' },
      { id: 'f_assembly_req', name: 'Assembly Required', key: 'assemblyRequired', type: 'boolean', defaultValue: true },
      { id: 'f_warranty_furn', name: 'Warranty Period', key: 'warranty', type: 'text', placeholder: 'e.g. 3 Years Structural' },
    ],
  },
  {
    id: 'wholesale_distributor',
    name: 'Wholesale / Distributor',
    icon: 'Truck',
    description: 'Bulk cartons, case packs, minimum order quantities (MOQ), tiered distributor pricing',
    category: 'WHOLESALE',
    defaultModules: ['billing', 'inventory', 'customers', 'suppliers', 'expenses', 'reports', 'gst', 'barcode'],
    defaultCategories: ['FMCG Bulk', 'Dry Groceries', 'Beverages (Cases)', 'Packaging Material', 'Plastic Goods', 'Bulk Supplies'],
    defaultUnits: ['Carton', 'Case', 'Pallet', 'Bundle', 'Bag', 'KG'],
    defaultTaxRate: 18,
    isSystem: true,
    customFields: [
      { id: 'f_case_qty', name: 'Units per Case / Carton', key: 'caseQuantity', type: 'number', placeholder: 'e.g. 24' },
      { id: 'f_moq', name: 'Minimum Order Qty (MOQ)', key: 'moq', type: 'number', placeholder: 'e.g. 5 Cartons' },
      { id: 'f_outer_barcode', name: 'Master Carton Barcode', key: 'outerBarcode', type: 'text', placeholder: 'Outer EAN/ITF Barcode' },
      { id: 'f_case_weight', name: 'Weight per Case (Kg)', key: 'caseWeight', type: 'text', placeholder: 'e.g. 15 Kg' },
    ],
  },
  {
    id: 'cosmetics_general',
    name: 'Cosmetics & General Store',
    icon: 'Sparkles',
    description: 'Skincare, makeup, perfumes, shade tones, batch dates, cruelty-free labels',
    category: 'RETAIL',
    defaultModules: ['billing', 'inventory', 'customers', 'suppliers', 'expenses', 'reports', 'gst', 'barcode'],
    defaultCategories: ['Skincare & Creams', 'Hair Care & Shampoos', 'Makeup & Cosmetics', 'Perfumes & Deos', 'Oral Care', 'Personal Hygiene'],
    defaultUnits: ['Piece', 'ML', 'Gram', 'Bottle', 'Box', 'Packet'],
    defaultTaxRate: 18,
    isSystem: true,
    customFields: [
      { id: 'f_skin_type', name: 'Skin Type Target', key: 'skinType', type: 'dropdown', options: ['All Skin Types', 'Dry Skin', 'Oily Skin', 'Sensitive', 'Normal'] },
      { id: 'f_shade_tone', name: 'Shade / Tone', key: 'shadeTone', type: 'text', placeholder: 'e.g. Shade 02 Sand / Natural Pink' },
      { id: 'f_cosm_expiry', name: 'Expiry Date', key: 'expiryDate', type: 'date' },
      { id: 'f_cruelty_free', name: 'Cruelty-Free / Organic', key: 'crueltyFree', type: 'boolean', defaultValue: true },
    ],
  },
  {
    id: 'dairy_milk',
    name: 'Dairy & Milk Products',
    icon: 'Milk',
    description: 'Fresh milk, paneer, curd, fat % SNF calculations, short shelf life, cold storage',
    category: 'RETAIL',
    defaultModules: ['billing', 'inventory', 'customers', 'suppliers', 'expenses', 'reports', 'gst', 'barcode'],
    defaultCategories: ['Fresh Milk', 'Paneer & Cheese', 'Curd & Chaas', 'Ghee & Butter', 'Ice Cream & Sweets', 'Flavoured Milk'],
    defaultUnits: ['Litre', 'ML', 'KG', 'Gram', 'Pouch', 'Bottle'],
    defaultTaxRate: 5,
    isSystem: true,
    customFields: [
      { id: 'f_fat_snf', name: 'Fat % / SNF', key: 'fatPercentage', type: 'text', placeholder: 'e.g. 6.0% Fat / 9.0% SNF' },
      { id: 'f_milk_type', name: 'Milk Type', key: 'milkType', type: 'dropdown', options: ['Cow Milk', 'Buffalo Milk', 'Full Cream', 'Toned Milk', 'Double Toned'] },
      { id: 'f_storage_temp', name: 'Storage Temperature (°C)', key: 'storageTemp', type: 'text', placeholder: 'e.g. Below 4°C' },
      { id: 'f_shelf_life_hours', name: 'Shelf Life (Hours)', key: 'shelfLifeHours', type: 'number', placeholder: '48' },
    ],
  },
];
