import { Product } from '@/types';

export function getInitialStockForBusinessType(businessTypeId: string, companyId: string): Product[] {
  const now = new Date().toISOString();
  const normalizedType = (businessTypeId || '').toLowerCase();

  // 1. MEDICAL / PHARMACY
  if (normalizedType === 'medical_pharmacy' || normalizedType.includes('medical') || normalizedType.includes('pharmacy')) {
    return [
      {
        id: `prod_med_1_${Date.now()}`,
        companyId,
        name: 'Dolo 650mg Paracetamol Tablets',
        sku: 'MED-DOLO-650',
        barcode: '890111700101',
        category: 'Tablets',
        brand: 'Micro Labs',
        businessTypeId: 'medical_pharmacy',
        unit: 'STRIP',
        purchasePrice: 24,
        sellingPrice: 30,
        mrp: 34,
        taxRate: 12,
        hsn: '3004',
        openingStock: 100,
        currentStock: 100,
        minStockAlert: 15,
        reorderLevel: 20,
        status: 'ACTIVE',
        trackInventory: true,
        trackBatch: true,
        trackExpiry: true,
        trackSerialNumber: false,
        batchNumber: 'DL-8821',
        mfgDate: '2026-01-10',
        expiryDate: '2028-05-30',
        customFields: { genericName: 'Paracetamol 650mg', manufacturer: 'Micro Labs', drugSchedule: 'OTC (General)' },
        createdAt: now,
        updatedAt: now,
      },
      {
        id: `prod_med_2_${Date.now()}`,
        companyId,
        name: 'Augmentin 625 Duo Tablets (Amoxyclav)',
        sku: 'MED-AUG-625',
        barcode: '890111700102',
        category: 'Tablets',
        brand: 'GSK',
        businessTypeId: 'medical_pharmacy',
        unit: 'STRIP',
        purchasePrice: 165,
        sellingPrice: 190,
        mrp: 205,
        taxRate: 12,
        hsn: '3004',
        openingStock: 40,
        currentStock: 40,
        minStockAlert: 10,
        reorderLevel: 15,
        status: 'ACTIVE',
        trackInventory: true,
        trackBatch: true,
        trackExpiry: true,
        trackSerialNumber: false,
        batchNumber: 'AUG-401',
        mfgDate: '2026-02-15',
        expiryDate: '2027-11-20',
        customFields: { genericName: 'Amoxicillin 500mg + Potassium Clavulanate 125mg', manufacturer: 'GSK', drugSchedule: 'Schedule H' },
        createdAt: now,
        updatedAt: now,
      },
      {
        id: `prod_med_3_${Date.now()}`,
        companyId,
        name: 'Benadryl Cough Syrup 100ml',
        sku: 'MED-BND-100',
        barcode: '890111700103',
        category: 'Syrups',
        brand: 'Johnson & Johnson',
        businessTypeId: 'medical_pharmacy',
        unit: 'BOTTLE',
        purchasePrice: 105,
        sellingPrice: 125,
        mrp: 135,
        taxRate: 12,
        hsn: '3004',
        openingStock: 50,
        currentStock: 50,
        minStockAlert: 10,
        reorderLevel: 15,
        status: 'ACTIVE',
        trackInventory: true,
        trackBatch: true,
        trackExpiry: true,
        trackSerialNumber: false,
        batchNumber: 'BND-901',
        mfgDate: '2026-03-01',
        expiryDate: '2028-02-28',
        customFields: { genericName: 'Diphenhydramine HCl + Ammonium Chloride', manufacturer: 'Johnson & Johnson', drugSchedule: 'OTC (General)' },
        createdAt: now,
        updatedAt: now,
      },
      {
        id: `prod_med_4_${Date.now()}`,
        companyId,
        name: 'Cetzine 10mg Tablets (Cetirizine)',
        sku: 'MED-CTZ-10',
        barcode: '890111700104',
        category: 'Tablets',
        brand: 'Dr. Reddy',
        businessTypeId: 'medical_pharmacy',
        unit: 'STRIP',
        purchasePrice: 14,
        sellingPrice: 19,
        mrp: 22,
        taxRate: 12,
        hsn: '3004',
        openingStock: 80,
        currentStock: 80,
        minStockAlert: 15,
        reorderLevel: 25,
        status: 'ACTIVE',
        trackInventory: true,
        trackBatch: true,
        trackExpiry: true,
        trackSerialNumber: false,
        batchNumber: 'CTZ-112',
        mfgDate: '2026-01-20',
        expiryDate: '2028-06-15',
        customFields: { genericName: 'Cetirizine HCl 10mg', manufacturer: 'Dr. Reddy Laboratories', drugSchedule: 'Schedule H' },
        createdAt: now,
        updatedAt: now,
      },
      {
        id: `prod_med_5_${Date.now()}`,
        companyId,
        name: 'Betadine 10% Ointment 20g',
        sku: 'MED-BTD-20G',
        barcode: '890111700105',
        category: 'Ointments',
        brand: 'Win-Medicare',
        businessTypeId: 'medical_pharmacy',
        unit: 'TUBE',
        purchasePrice: 65,
        sellingPrice: 78,
        mrp: 85,
        taxRate: 12,
        hsn: '3004',
        openingStock: 35,
        currentStock: 35,
        minStockAlert: 8,
        reorderLevel: 12,
        status: 'ACTIVE',
        trackInventory: true,
        trackBatch: true,
        trackExpiry: true,
        trackSerialNumber: false,
        batchNumber: 'BTD-330',
        mfgDate: '2026-02-05',
        expiryDate: '2027-09-30',
        customFields: { genericName: 'Povidone Iodine 10% w/w', manufacturer: 'Win-Medicare', drugSchedule: 'OTC (General)' },
        createdAt: now,
        updatedAt: now,
      },
      {
        id: `prod_med_6_${Date.now()}`,
        companyId,
        name: 'Omez 20mg Gastro-Resistant Capsules',
        sku: 'MED-OMZ-20',
        barcode: '890111700106',
        category: 'Capsules',
        brand: 'Dr. Reddy',
        businessTypeId: 'medical_pharmacy',
        unit: 'STRIP',
        purchasePrice: 42,
        sellingPrice: 52,
        mrp: 58,
        taxRate: 12,
        hsn: '3004',
        openingStock: 60,
        currentStock: 60,
        minStockAlert: 12,
        reorderLevel: 18,
        status: 'ACTIVE',
        trackInventory: true,
        trackBatch: true,
        trackExpiry: true,
        trackSerialNumber: false,
        batchNumber: 'OMZ-771',
        mfgDate: '2026-02-18',
        expiryDate: '2028-04-10',
        customFields: { genericName: 'Omeprazole IP 20mg', manufacturer: 'Dr. Reddy Laboratories', drugSchedule: 'Schedule H' },
        createdAt: now,
        updatedAt: now,
      },
    ];
  }

  // 2. KIRANA / GROCERY STORE
  if (normalizedType === 'kirana' || normalizedType.includes('kirana') || normalizedType.includes('grocery')) {
    return [
      {
        id: `prod_kir_1_${Date.now()}`,
        companyId,
        name: 'Aashirvaad Superior MP Shudh Chakki Atta 10kg',
        sku: 'KIR-ATTA-10K',
        barcode: '890103001001',
        category: 'Grains & Pulses',
        brand: 'Aashirvaad',
        businessTypeId: 'kirana',
        unit: 'BAG',
        purchasePrice: 395,
        sellingPrice: 435,
        mrp: 460,
        taxRate: 0,
        hsn: '1101',
        openingStock: 30,
        currentStock: 30,
        minStockAlert: 5,
        reorderLevel: 10,
        status: 'ACTIVE',
        trackInventory: true,
        trackBatch: true,
        trackExpiry: true,
        trackSerialNumber: false,
        batchNumber: 'BATCH-AT26',
        mfgDate: '2026-03-01',
        expiryDate: '2026-09-01',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: `prod_kir_2_${Date.now()}`,
        companyId,
        name: 'Fortune Sunlite Refined Sunflower Oil 1L Pouch',
        sku: 'KIR-OIL-1L',
        barcode: '890103001002',
        category: 'Oils & Ghee',
        brand: 'Fortune',
        businessTypeId: 'kirana',
        unit: 'POUCH',
        purchasePrice: 120,
        sellingPrice: 135,
        mrp: 145,
        taxRate: 5,
        hsn: '1512',
        openingStock: 45,
        currentStock: 45,
        minStockAlert: 10,
        reorderLevel: 15,
        status: 'ACTIVE',
        trackInventory: true,
        trackBatch: true,
        trackExpiry: true,
        trackSerialNumber: false,
        batchNumber: 'FO-551',
        mfgDate: '2026-02-10',
        expiryDate: '2026-11-10',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: `prod_kir_3_${Date.now()}`,
        companyId,
        name: 'Tata Salt Vacuum Evaporated Iodised 1kg',
        sku: 'KIR-SALT-1K',
        barcode: '890103001003',
        category: 'Spices',
        brand: 'Tata',
        businessTypeId: 'kirana',
        unit: 'PKT',
        purchasePrice: 22,
        sellingPrice: 26,
        mrp: 28,
        taxRate: 0,
        hsn: '2501',
        openingStock: 60,
        currentStock: 60,
        minStockAlert: 15,
        reorderLevel: 25,
        status: 'ACTIVE',
        trackInventory: true,
        trackBatch: false,
        trackExpiry: false,
        trackSerialNumber: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: `prod_kir_4_${Date.now()}`,
        companyId,
        name: 'Daawat Rozana Super Basmati Rice 5kg',
        sku: 'KIR-RICE-5K',
        barcode: '890103001004',
        category: 'Grains & Pulses',
        brand: 'Daawat',
        businessTypeId: 'kirana',
        unit: 'BAG',
        purchasePrice: 320,
        sellingPrice: 360,
        mrp: 399,
        taxRate: 5,
        hsn: '1006',
        openingStock: 25,
        currentStock: 25,
        minStockAlert: 5,
        reorderLevel: 10,
        status: 'ACTIVE',
        trackInventory: true,
        trackBatch: false,
        trackExpiry: false,
        trackSerialNumber: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: `prod_kir_5_${Date.now()}`,
        companyId,
        name: 'Amul Butter Pasteurized 500g Pack',
        sku: 'KIR-BUTTER-500G',
        barcode: '890103001005',
        category: 'Dairy',
        brand: 'Amul',
        businessTypeId: 'kirana',
        unit: 'PKT',
        purchasePrice: 245,
        sellingPrice: 265,
        mrp: 275,
        taxRate: 12,
        hsn: '0405',
        openingStock: 20,
        currentStock: 20,
        minStockAlert: 5,
        reorderLevel: 8,
        status: 'ACTIVE',
        trackInventory: true,
        trackBatch: true,
        trackExpiry: true,
        trackSerialNumber: false,
        batchNumber: 'AML-099',
        mfgDate: '2026-03-05',
        expiryDate: '2026-06-05',
        createdAt: now,
        updatedAt: now,
      },
    ];
  }

  // 3. ELECTRONICS & MOBILE
  if (normalizedType === 'electronics_mobile' || normalizedType.includes('electronics') || normalizedType.includes('mobile')) {
    return [
      {
        id: `prod_elec_1_${Date.now()}`,
        companyId,
        name: 'OnePlus Nord CE4 5G (8GB/128GB)',
        sku: 'ELEC-OP-NORD-128',
        barcode: '890204001001',
        category: 'Smartphones',
        brand: 'OnePlus',
        businessTypeId: 'electronics_mobile',
        unit: 'PCS',
        purchasePrice: 20500,
        sellingPrice: 22999,
        mrp: 24999,
        taxRate: 18,
        hsn: '8517',
        openingStock: 12,
        currentStock: 12,
        minStockAlert: 3,
        reorderLevel: 5,
        status: 'ACTIVE',
        trackInventory: true,
        trackBatch: false,
        trackExpiry: false,
        trackSerialNumber: true,
        serialNumber: 'IMEI-869281092837190',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: `prod_elec_2_${Date.now()}`,
        companyId,
        name: 'boAt Airdopes 141 True Wireless Earbuds',
        sku: 'ELEC-BOAT-141',
        barcode: '890204001002',
        category: 'Audio & Earbuds',
        brand: 'boAt',
        businessTypeId: 'electronics_mobile',
        unit: 'PCS',
        purchasePrice: 950,
        sellingPrice: 1299,
        mrp: 2990,
        taxRate: 18,
        hsn: '8518',
        openingStock: 30,
        currentStock: 30,
        minStockAlert: 5,
        reorderLevel: 10,
        status: 'ACTIVE',
        trackInventory: true,
        trackBatch: false,
        trackExpiry: false,
        trackSerialNumber: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: `prod_elec_3_${Date.now()}`,
        companyId,
        name: 'Samsung 25W Type-C Super Fast Travel Charger',
        sku: 'ELEC-SAM-25W',
        barcode: '890204001003',
        category: 'Chargers & Accessories',
        brand: 'Samsung',
        businessTypeId: 'electronics_mobile',
        unit: 'PCS',
        purchasePrice: 850,
        sellingPrice: 1199,
        mrp: 1699,
        taxRate: 18,
        hsn: '8504',
        openingStock: 25,
        currentStock: 25,
        minStockAlert: 5,
        reorderLevel: 10,
        status: 'ACTIVE',
        trackInventory: true,
        trackBatch: false,
        trackExpiry: false,
        trackSerialNumber: false,
        createdAt: now,
        updatedAt: now,
      },
    ];
  }

  // 4. GARMENTS & FOOTWEAR
  if (normalizedType === 'garments_footwear' || normalizedType.includes('garments') || normalizedType.includes('footwear')) {
    return [
      {
        id: `prod_garm_1_${Date.now()}`,
        companyId,
        name: "Men's Slim Fit Pure Cotton Formal Shirt (L)",
        sku: 'GARM-SHIRT-L',
        barcode: '890305001001',
        category: "Men's Wear",
        brand: 'Peter England',
        businessTypeId: 'garments_footwear',
        unit: 'PCS',
        purchasePrice: 650,
        sellingPrice: 999,
        mrp: 1499,
        taxRate: 5,
        hsn: '6205',
        openingStock: 25,
        currentStock: 25,
        minStockAlert: 5,
        reorderLevel: 8,
        status: 'ACTIVE',
        trackInventory: true,
        trackBatch: false,
        trackExpiry: false,
        trackSerialNumber: false,
        customFields: { size: 'L', color: 'Sky Blue', fabric: 'Pure Cotton' },
        createdAt: now,
        updatedAt: now,
      },
      {
        id: `prod_garm_2_${Date.now()}`,
        companyId,
        name: 'Sparx Men Running / Walking Sports Shoes UK-8',
        sku: 'GARM-SPARX-UK8',
        barcode: '890305001002',
        category: 'Footwear (Men)',
        brand: 'Sparx',
        businessTypeId: 'garments_footwear',
        unit: 'PAIR',
        purchasePrice: 780,
        sellingPrice: 1149,
        mrp: 1399,
        taxRate: 5,
        hsn: '6404',
        openingStock: 18,
        currentStock: 18,
        minStockAlert: 4,
        reorderLevel: 6,
        status: 'ACTIVE',
        trackInventory: true,
        trackBatch: false,
        trackExpiry: false,
        trackSerialNumber: false,
        customFields: { size: 'UK-8', color: 'Black/Grey' },
        createdAt: now,
        updatedAt: now,
      },
    ];
  }

  // 5. GENERIC / CUSTOM
  return [
    {
      id: `prod_gen_1_${Date.now()}`,
      companyId,
      name: 'Standard Store Inventory Item 01',
      sku: 'SKU-00101',
      barcode: '890999001001',
      category: 'General',
      businessTypeId,
      unit: 'PCS',
      purchasePrice: 100,
      sellingPrice: 150,
      mrp: 180,
      taxRate: 18,
      hsn: '9999',
      openingStock: 20,
      currentStock: 20,
      minStockAlert: 5,
      reorderLevel: 8,
      status: 'ACTIVE',
      trackInventory: true,
      trackBatch: false,
      trackExpiry: false,
      trackSerialNumber: false,
      createdAt: now,
      updatedAt: now,
    },
  ];
}
