import { SubscriptionPlan, PlanId, ModuleKey } from '@/types';

export interface SaaSFeature {
  id: string;
  name: string;
  category: 'Billing & POS' | 'Inventory' | 'Khata & Customers' | 'Staff & Operations' | 'Compliance & Support';
  description: string;
}

// 16 Standard SaaS Features Defined by User
export const SAAS_FEATURES: SaaSFeature[] = [
  { id: 'billing_invoice', name: 'Billing & Invoice', category: 'Billing & POS', description: 'Fast POS cashier billing with multi-payment mode support' },
  { id: 'a4_smart_invoice', name: 'A4 Smart Invoice', category: 'Billing & POS', description: 'Full-page professional A4 invoice with logo, GST, terms & bank details' },
  { id: 'thermal_bill_58mm', name: '58mm Thermal Bill', category: 'Billing & POS', description: 'Instant 2-inch (58mm) & 3-inch (80mm) thermal receipt printing' },
  { id: 'stock_inventory', name: 'Stock / Inventory', category: 'Inventory', description: 'Real-time stock tracking, low stock alerts & inventory ledger' },
  { id: 'customer_master', name: 'Customer Master List', category: 'Khata & Customers', description: 'Comprehensive customer directory with contact cards and purchase history' },
  { id: 'sold_item_return', name: 'Sold Item Return', category: 'Billing & POS', description: 'Credit note creation, return voucher generation & auto stock restitution' },
  { id: 'sundry_khatabook', name: 'Sundry Khatabook (Dues)', category: 'Khata & Customers', description: 'Udhaar ledger, customer credit limits, payment reminders & due tracking' },
  { id: 'collection_agent', name: 'Collection Agent', category: 'Staff & Operations', description: 'Field collection agent login, on-door receipt creation & dues clearance' },
  { id: 'stock_challan', name: 'Stock Challan', category: 'Inventory', description: 'Delivery challan creation, branch dispatch & movement tracking' },
  { id: 'invoice_draft', name: 'Invoice Draft', category: 'Billing & POS', description: 'Save counter carts as draft and resume billing anytime' },
  { id: 'reports_export', name: 'Reports & Export', category: 'Compliance & Support', description: 'Sales, Profit/Loss, Stock Valuation & Cashflow reports' },
  { id: 'excel_import_export', name: 'Excel Import / Export', category: 'Inventory', description: 'Bulk product catalog uploads and customer Excel/CSV data exports' },
  { id: 'upi_qr_bill', name: 'UPI QR on Bill', category: 'Billing & POS', description: 'Dynamic NPCI UPI QR printed on invoice for instant mobile phone payment' },
  { id: 'counter_staff_roles', name: 'Counter Staff & Roles', category: 'Staff & Operations', description: 'Cashier, manager & inventory staff logins with granular access control' },
  { id: 'gst_tax_calc', name: 'GST Tax Calculation', category: 'Compliance & Support', description: 'Automated CGST, SGST, IGST split & HSN B2B/B2C tax computation' },
  { id: 'support_ticket_desk', name: 'Support Ticket Desk', category: 'Compliance & Support', description: 'Direct in-app priority help desk ticketing with NPB Media team' },
];

export const PRESET_PLANS: SubscriptionPlan[] = [
  {
    id: 'BASIC',
    name: 'Basic',
    price: 0,
    priceMonthly: 0,
    priceYearly: 0,
    validityDays: 30,
    planType: 'free',
    description: 'Entry tier for single-counter retail shops and testing',
    features: ['50 Products Limit', '100 Customers Limit', '1 Staff Login', '1 Branch Outlet', 'Billing & Invoice', '58mm Thermal Bill', 'A4 Smart Invoice'],
    includedFeatureIds: [
      'billing_invoice',
      'a4_smart_invoice',
      'thermal_bill_58mm',
      'customer_master',
      'upi_qr_bill',
      'gst_tax_calc',
    ],
    autoEnabledModules: ['billing', 'inventory', 'customers', 'gst'],
    limits: {
      maxProducts: 50,
      isUnlimitedProducts: false,
      maxEmployees: 1,
      maxCustomers: 100,
      isUnlimitedCustomers: false,
      maxSuppliers: 10,
      maxInvoicesPerMonth: 200,
      maxBranches: 1,
      aiAssistant: false,
      whatsappAlerts: false,
      advancedReports: false,
      storageMb: 100,
    },
  },
  {
    id: 'STANDARD',
    name: 'Standard',
    price: 1199,
    priceMonthly: 1199,
    priceYearly: 1199,
    validityDays: 365,
    planType: 'paid',
    description: 'For growing retail stores requiring barcode billing, dues khata and stock tracking',
    features: ['Unlimited Products', 'Unlimited Customers', '3 Staff Logins', '1 Branch Outlet', 'Stock Management', 'Customer Khata', 'Barcode Billing'],
    includedFeatureIds: [
      'billing_invoice',
      'a4_smart_invoice',
      'thermal_bill_58mm',
      'stock_inventory',
      'customer_master',
      'sold_item_return',
      'sundry_khatabook',
      'invoice_draft',
      'reports_export',
      'upi_qr_bill',
      'gst_tax_calc',
    ],
    autoEnabledModules: ['billing', 'inventory', 'customers', 'suppliers', 'reports', 'gst', 'barcode'],
    limits: {
      maxProducts: 100000,
      isUnlimitedProducts: true,
      maxEmployees: 3,
      maxCustomers: 100000,
      isUnlimitedCustomers: true,
      maxSuppliers: 100,
      maxInvoicesPerMonth: 5000,
      maxBranches: 1,
      aiAssistant: false,
      whatsappAlerts: true,
      advancedReports: false,
      storageMb: 500,
    },
  },
  {
    id: 'PREMIUM',
    name: 'Premium',
    price: 2999,
    priceMonthly: 2999,
    priceYearly: 2999,
    validityDays: 365,
    planType: 'paid',
    description: 'Most popular for supermarkets, multi-counter stores and distribution businesses',
    features: ['Unlimited Products', 'Unlimited Customers', '5 Staff Logins', '3 Branch Outlets', 'AI Business Assistant', 'WhatsApp & SMS Invoicing', 'Stock Challans', 'Collection Agent'],
    includedFeatureIds: [
      'billing_invoice',
      'a4_smart_invoice',
      'thermal_bill_58mm',
      'stock_inventory',
      'customer_master',
      'sold_item_return',
      'sundry_khatabook',
      'collection_agent',
      'stock_challan',
      'invoice_draft',
      'reports_export',
      'excel_import_export',
      'upi_qr_bill',
      'counter_staff_roles',
      'gst_tax_calc',
      'support_ticket_desk',
    ],
    autoEnabledModules: [
      'billing',
      'inventory',
      'customers',
      'suppliers',
      'expenses',
      'employees',
      'attendance',
      'reports',
      'gst',
      'barcode',
      'returns',
      'branches',
      'ai',
      'whatsapp',
    ],
    limits: {
      maxProducts: 100000,
      isUnlimitedProducts: true,
      maxEmployees: 5,
      maxCustomers: 100000,
      isUnlimitedCustomers: true,
      maxSuppliers: 500,
      maxInvoicesPerMonth: 25000,
      maxBranches: 3,
      aiAssistant: true,
      whatsappAlerts: true,
      advancedReports: true,
      storageMb: 2000,
    },
  },
  {
    id: 'ENTERPRISE',
    name: 'Enterprise',
    price: 7999,
    priceMonthly: 7999,
    priceYearly: 7999,
    validityDays: 365,
    planType: 'paid',
    description: 'Large retail chains, multi-city wholesale, custom integrations and dedicated SLA',
    features: ['Unlimited Products & Customers', '20 Staff Logins', '10 Branch Outlets', 'All 16 Feature Modules', 'Dedicated AI Assistant', 'Priority Support Desk'],
    includedFeatureIds: [
      'billing_invoice',
      'a4_smart_invoice',
      'thermal_bill_58mm',
      'stock_inventory',
      'customer_master',
      'sold_item_return',
      'sundry_khatabook',
      'collection_agent',
      'stock_challan',
      'invoice_draft',
      'reports_export',
      'excel_import_export',
      'upi_qr_bill',
      'counter_staff_roles',
      'gst_tax_calc',
      'support_ticket_desk',
    ],
    autoEnabledModules: [
      'billing',
      'inventory',
      'customers',
      'suppliers',
      'expenses',
      'employees',
      'attendance',
      'reports',
      'gst',
      'barcode',
      'returns',
      'branches',
      'ai',
      'whatsapp',
      'notifications',
      'advancedReports',
    ],
    limits: {
      maxProducts: 1000000,
      isUnlimitedProducts: true,
      maxEmployees: 20,
      maxCustomers: 1000000,
      isUnlimitedCustomers: true,
      maxSuppliers: 10000,
      maxInvoicesPerMonth: 200000,
      maxBranches: 10,
      aiAssistant: true,
      whatsappAlerts: true,
      advancedReports: true,
      storageMb: 10000,
    },
  },
];

export function getAutoAssignedModulesForPlan(planId: PlanId, planList?: SubscriptionPlan[]): ModuleKey[] {
  let plan = planList?.find((p) => p.id === planId);
  if (!plan) {
    plan = PRESET_PLANS.find((p) => p.id === planId);
  }
  return plan?.autoEnabledModules || ['billing', 'inventory', 'customers', 'suppliers', 'reports', 'gst'];
}

export function getAutoAssignedFeaturesForPlan(planId: PlanId, planList?: SubscriptionPlan[]): SaaSFeature[] {
  let plan = planList?.find((p) => p.id === planId);
  if (!plan) {
    plan = PRESET_PLANS.find((p) => p.id === planId);
  }
  const ids = plan?.includedFeatureIds || [];
  return SAAS_FEATURES.filter((f) => ids.includes(f.id));
}
